# Generated by Django 3.0.2 on 2020-01-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('effort', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('New', 'New'), ('Ready', 'Ready'), ('InProgress', 'In Progress'), ('Done', 'Done')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workmanager.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
