# Generated by Django 3.0.2 on 2020-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0002_auto_20200110_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
